### ISSUE TITLE
论文咨询

### ISSUE THREAD

**Issue by lebron-2016** [corfyi/UCMCTrack#1]
尊敬的作者您好：

我学习了您的论文，获得了很大的启发。但是有两个小问题希望向您请教一下。

第一个是，您提到对于同一个视频序列只需使用一组相机运动补偿参数，这里的参数是指相机的内外参矩阵吗？假如相机发生了比较剧烈的不规则运动，不使用帧间运动补偿，您的算法是如何保证跟踪稳定性的呢？

第二个是关于相机参数的估计，想问下您是采用什么方法进行估计的呢？针对测试集数据如何进行估计？

期待您的回复！！

万分感谢！！

**Comment by corfyi** [comment]
1、请阅读论文的章节Process Noise Compensation部分，通过补偿因子wx, wy来补偿相机的运动。论文里对视频序列的相机运动情况做了一个先验假设，对于相机左右旋转的情况，wy需要调大一些，对于相机俯仰旋转（或者相机前后平移）的情况，wx要调大一些；对于相机不运动的情况，wx和wy要调小一些。图4.a对这个问题有所讨论。

2、我们通过手动调节参数获取测试集数据上相机相对地平面外参的粗略估计，有一个非常简单有效的实现，相机参数估计的代码在后续计划放出来，请持续关注。
