### ISSUE TITLE
Fully Automative way to estimate  Estimated Camera Parameters

### ISSUE THREAD

**Issue by PraveenSuryawanshi-Dev** [corfyi/UCMCTrack#10]
Hello Corfyi,

Your efforts has great potential to integrate into fully automated systems,  I'm bit worried about setting the camera parameter using a manual activities.

Is there a way to fully automat the estimatimation of  Camera Parameters and run the tracker ?

Thanks in advance.

**Comment by corfyi** [comment]
Thank you for reaching out and for your interest in our project.

Currently, our camera parameter estimation tool does rely on manual adjustments to roughly align with the ground plane. I understand your concern about automating this process for integration into fully automated systems. We have plans to develop a method based on neural networks to further enhance the level of automation in future updates. This should greatly simplify the camera parameter estimation process and make it more efficient for users like yourself.

Please stay tuned for these upcoming developments. If you find our current work and future plans beneficial, consider giving our project a star on GitHub. Your support is not only encouraging but also helps others in the community discover and use our tools effectively.

**Comment by PraveenSuryawanshi-Dev** [comment]
Thank you so much Corfyi for reaching out to me and providing a quick response.

Its great to hear that you have already planned my concern.

Can you take this into priority and work on it. since  I believe it will usefull to others.

Also can you provide some time line till when it will be done?

**Comment by PraveenSuryawanshi-Dev** [comment]
Thanks Corfyi,  sharing your thoughts to my concerns.
I would be watching till then.
