### ISSUE TITLE
Using the GMC in BotSort 

### ISSUE THREAD

**Issue by congyao123456** [corfyi/UCMCTrack#12]
Hi author thanks for your contribution to MOT, I have a question, in the paper it says to use only one set of the same parameters in a video for motion camera compensation, but you used the GMC file in botsort in the source code, isn't that method compensated frame by frame?

作者你好感谢你对MOT做出的贡献，我有一个疑问，论文当中说在一个视频中只使用一套相同的参数进行运动相机补偿，而你在源代码中使用了botsort中的GMC文件，该方法不是逐帧进行补偿的吗

**Comment by corfyi** [comment]
Thank you for your interest in our work and for bringing up this insightful query regarding motion camera compensation in our MOT project.

In our paper, we indeed discuss and compare frame-by-frame Camera Motion Compensation (CMC) and Uniform Camera Motion Compensation (UCMC) in Table 5. Through our research, particularly on the MOT17 dataset, we discovered that combining UCMC with CMC yields better results. We refer to the approach using CMC as **UCMCTrack+**. Consequently, we utilized the GMC file in our implementation for MOT17.

However, it's important to note that the effectiveness of this method varies with different datasets. For instance, in DancTrack, MOT20, and KiTTI datasets, we found that UCMCTrack without the use of GMC files outperforms the version that incorporates GMC. 

I hope this clarifies our methodology and the rationale behind using the GMC file in certain cases. If you find our research and methods useful, please consider supporting us by starring our project on GitHub. Your support greatly helps us in continuing our work in this field.

**Comment by congyao123456** [comment]
> 感谢您对我们工作的关注，并就我们的 MOT 项目中的运动摄像机补偿提出这个有见地的问题。
> 
> 在我们的论文中，我们确实在表5中讨论和比较了逐帧相机运动补偿（CMC）和统一相机运动补偿（UCMC）。通过我们的研究，特别是在MOT17数据集上，我们发现将UCMC与CMC相结合会产生更好的结果。我们将使用 CMC 的方法称为 **UCMCTrack+**。因此，我们在 MOT17 的实现中使用了 GMC 文件。
> 
> 但是，需要注意的是，这种方法的有效性因不同的数据集而异。例如，在 DancTrack、MOT20 和 KiTTI 数据集中，我们发现不使用 GMC 文件的 UCMCTrack 优于包含 GMC 的版本。
> 
> 我希望这能澄清我们的方法和在某些情况下使用 GMC 文件背后的基本原理。如果您发现我们的研究和方法有用，请考虑通过在 GitHub 上为我们的项目加星标来支持我们。您的支持极大地帮助我们继续在这一领域的工作。

I see, thanks for the reply and I hope you keep up the good work on your MOT tasks!
