### ISSUE TITLE
MOT det

### ISSUE THREAD

**Issue by ydhcg-BoBo** [corfyi/UCMCTrack#14]

**Comment by ydhcg-BoBo** [comment]
请教一下作者，det_results文件夹中的结果，是采用bytetrack训练好的权重直接得到的检测结果吗？这个过程有进行其他的处理吗？谢谢！

**Comment by corfyi** [comment]
Thank you for reaching out with your question about the `det_results` folder in our project.

The detection results in the `det_results` folder are indeed obtained using weights trained with ByteTrack. These results are generated directly from the ByteTrack detector without any additional post-processing or modification. 

The process is straightforward: we apply the ByteTrack detector to the relevant datasets, and the resulting detection outputs are saved in the `det_results` folder. This approach allows us to focus on the tracking aspect of our project while leveraging the robust detection capabilities of ByteTrack.
