### ISSUE TITLE
论文关于矩阵G的讨论

### ISSUE THREAD

**Issue by piggi999** [corfyi/UCMCTrack#17]
作者您好，非常感谢您开源的工作。最近在阅读您论文的时候我发现了一些可能的错误，您在Process Noise Compensation章节中所求取的G矩阵中蕴含的滤波器状态量表述似乎与论文说写的state vector=[x, y, x', y']不一致。按照论文中提供的G矩阵所求取的，应当是状态量[x, x', y, y']的过程噪声矩阵。如果以上我说错了什么或者误解了什么，请麻烦告诉我，再次感谢您的工作。
-----------------------------------------------------------------------------------------------------------------------------
作者你好，我跟楼主有一样的疑问，如果论文中的顺序有误应该是[x, x', y, y']， 但是代码中我看kf.x表示的是[x, y, x', y']，而G表示的是[x, x', y, y']的过程噪声矩阵，这是不是代码有问题？还是G是有其他的含义？期待您的回复，感谢！

**Comment by corfyi** [comment]
Thank you for pointing out this matter. Yes, we have acknowledged the error and have recently updated our paper on arXiv with the necessary corrections. We appreciate your attention to detail and your contribution to improving the quality of our work.

You can find the revised version of the paper on arXiv now. We hope that the update addresses your concerns and provides clearer information.

If you find our research and continuous efforts to maintain accuracy and quality helpful, please consider supporting us by starring our project on GitHub. Your support not only encourages our team but also helps in increasing the visibility of our work within the community.

**Comment by piggi999** [comment]
那代码是也有问题吗？
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2024年02月01日 08:56 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [corfyi/UCMCTrack] 论文关于矩阵G的讨论 (Issue #17) 
Thank you for pointing out this matter. Yes, we have acknowledged the error and have recently updated our paper on arXiv with the necessary corrections. We appreciate your attention to detail and your contribution to improving the quality of our work.
You can find the revised version of the paper on arXiv now. We hope that the update addresses your concerns and provides clearer information.
If you find our research and continuous efforts to maintain accuracy and quality helpful, please consider supporting us by starring our project on GitHub. Your support not only encourages our team but also helps in increasing the visibility of our work within the community.

**Comment by corfyi** [comment]
The code and the updated paper are aligned in their descriptions and implementations.

**Comment by piggi999** [comment]
谢谢你的回复。请问你能再详细介绍一下图3中每个椭圆代表的含义吗？ 为什么每个子图有两个相同颜色的图？

**Comment by piggi999** [comment]
请问在消融实验中，没有使用Process Noise Compensation时，过程噪声矩阵是什么呀？

**Comment by piggi999** [comment]
请问可以详细讲讲图4 c)中的实验做法吗？

**Comment by corfyi** [comment]
图3中每个椭圆代表的是检测值投影到地平面上的不确定性分布（二维高斯分布）；消融实验中没有使用Process Noise Compensation时，过程噪声矩阵中的wx和wy没有针对相机运动程度进行调参。
