### ISSUE TITLE
a question for function getUVError

### ISSUE THREAD

**Issue by LSH9832** [corfyi/UCMCTrack#20]
The following function is defined in file [detector/mapper.py](https://github.com/corfyi/UCMCTrack/blob/master/detector/mapper.py#L6). Why u and v are both equal to 0.05 * bbox_height?
```python
def getUVError(box):
    u = 0.05*box[3]
    v = 0.05*box[3]
    if u>13:
        u = 13
    elif u<2:
        u = 2
    if v>10:
        v = 10
    elif v<2:
        v = 2
    return u,v
```

**Comment by corfyi** [comment]
It appears to be an oversight in the implementation. In practice, using either bbox_height or bbox_width should yield similar results.
