### ISSUE TITLE
What is z0 and why is it =-1.73 in the Kitti dataset?

### ISSUE THREAD

**Issue by rslim97** [corfyi/UCMCTrack#22]
https://github.com/corfyi/UCMCTrack/blob/e2ad836216c8edba5f4166c80e5cff9e042380d5/detector/mapper.py#L92C1-L100C19

how to determine z0?

**Comment by corfyi** [comment]
The KITTI dataset provides a mapping matrix from 3D coordinates to 2D coordinates, where z0 represents the height offset of the ground plane relative to the 3D Lidar sensor. For more details, please refer to the KITTI official website.

**Comment by rslim97** [comment]
thanks @corfyi for clarifying.
