### ISSUE TITLE
论文的疑惑

### ISSUE THREAD

**Issue by ziyannnnn** [corfyi/UCMCTrack#3]
作者您好，非常感谢您开源的工作。最近在阅读您论文的时候我发现了一些可能的错误，您在`Process Noise Compensation`章节中所求取的G矩阵中蕴含的滤波器状态量表述似乎与论文说写的state vector=[x, y, x', y']不一致。按照论文中提供的G矩阵所求取的，应当是状态量[x, x', y, y']的过程噪声矩阵。如果以上我说错了什么或者误解了什么，请麻烦告诉我，再次感谢您的工作。

**Comment by corfyi** [comment]
是的，正文中状态量的正确顺序应该是[x, x', y, y']

**Comment by piggi999** [comment]
作者你好，我跟楼主有一样的疑问，如果论文中的顺序有误应该是[x, x', y, y']， 但是代码中我看kf.x表示的是[x, y, x', y']，而G表示的是[x, x', y, y']的过程噪声矩阵，这是不是代码有问题？还是G是有其他的含义？期待您的回复，感谢！
