### ISSUE TITLE
Camera Parameter Estimation Tool

### ISSUE THREAD

**Issue by shreejalt** [corfyi/UCMCTrack#6]
Thanks for the great work.
I wanted to know then when will you open source the parameter estimation tool that is mentioned in README? The approach seems interesting to me.

**Comment by corfyi** [comment]
Thank you for your interest in our project and for the kind words!

I'm pleased to inform you that the camera parameter estimation tool mentioned in the README has already been open-sourced. You can use it with the following command:

```
python util/estimate_cam_para.py --img demo/demo.jpg --cam_para demo/cam_para_test.txt
```

In this tool, `demo/demo.jpg` is a single image drawn from a video sequence with unknown camera parameters. By adjusting parameters like `theta_x`, `theta_y`, `theta_z`, `focal`, and `t_x` in the UI window, you can align a virtual ground plane grid with the ground in the image. This process will provide you with an estimation of the camera parameters. While this estimation might not be extremely precise, it is sufficiently accurate for use with UCMCTrack.

Feel free to give it a try and let us know if you have any further questions or feedback!

**Comment by shreejalt** [comment]
@corfyi Thanks for the quick response. Can you help me find an UI which you have shown in the readme?  Aslo the cam_para_test.txt are which parameters? Are rhouse dummy params or the parameters of the site after calibration?

**Comment by corfyi** [comment]
1. **Updated Usage Tutorial in README:** I've updated the README file with a detailed tutorial on how to use the Camera Parameter Estimation Tool. This should guide you through the process step-by-step, making it easier to understand and implement.

2. **About `cam_para_test.txt`:** The `cam_para_test.txt` file contains 'dummy parameters' (placeholders or example values) to start with. You'll need to modify one of these parameters initially — specifically, the camera's midpoint. This can be easily determined based on the size of your photo. Once you've adjusted this initial parameter, you can use the UI tool to tweak the other parameters. This process will provide you with a rough estimate of the camera parameters, which will then be saved back into the `cam_para_test.txt` file.

I hope this helps to clarify your concerns. Please don't hesitate to reach out if you have more questions or need further assistance.
