### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by wyc0509** [corfyi/UCMCTrack#8]
您好，有个问题咨询一下，拜读了您的代码，发现您是一个视频序列使用一套固定的相机参数是嘛，我看您给的demo图片应该是来自visdrone数据集？对于这类视频序列里相机位置和视角变化很大的无人机数据集，您这套方法依然有效嘛，因为看您没在论文里提到，请问您有针对visdrone或者uavdt这类数据集做实验嘛，期待您的回复，谢谢！

**Comment by corfyi** [comment]
Thank you for your interest in our project and for reaching out with your question.

Regarding your inquiry, yes, the demo video is indeed from the VisDrone dataset. For scenarios with camera motion, like in the VisDrone dataset, UCMCTrack utilizes a fixed set of camera parameters and still achieves commendable results. We have conducted experiments on the KITTI dataset, where the camera is mounted on a moving vehicle, resulting in more dramatic motion. The results were quite satisfactory there too.

Although we haven't performed a comprehensive evaluation on the VisDrone dataset, the performance on the provided video demo seems promising. I encourage you to try it out yourself with different sequences and see how it performs.

If you find the tool and its applications useful,  it would be wonderful if you could consider giving the project a star on GitHub. Your support not only motivates us but also helps others in the community discover our work, which we hope can be beneficial to many.
