### ISSUE TITLE
How to use YOLOX model in the place of YOLOv8x

### ISSUE THREAD

**Issue by tericalpha** [corfyi/UCMCTrack#9]
@corfyi  , I need to use the YOLOX model instead of this YOLOv8x model.
Can you please suggest me the approach.

**Comment by corfyi** [comment]
As of now, the Ultralytics Library does not include the YOLOX model. Therefore, integrating YOLOX into our demo can be a bit tricky. However, current SOTA algorithms for pedestrian datasets indeed use YOLOX detector, but their codes are quite tightly coupled, making direct adaptation of YOLOX model a complex task.

Nevertheless, I'd like to inform you that the `det_results` directory in our project contains files that are actually obtained using the YOLOX detector. You can use these pre-detected results for your immediate needs while we work on integrating a YOLOX-based demo. This should provide a temporary solution and also give you an insight into the performance you can expect.

Understanding the importance and potential benefits of YOLOX, we are planning to develop a demo based on the YOLOX model in the near future. We encourage you to stay tuned for this update.

If you find our work and forthcoming updates valuable, please consider giving our project a star on GitHub. Your support not only encourages us but also helps others in the community find and utilize our resources. We appreciate your interest and look forward to bringing you more useful features soon!
